### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by scilganon** [Sseryyz/tic_tak_toe#4]
0f991ea6f80cc3f69594da24976b60287d9bc354

- move all html creation to js
- replace html from js to template-tags (no `...innerHtml += "<div>...</div>"`)
- check win conditions over using stored win-lines in arrays, like 

```
const wins = [
        [0,1,2],
        [3,4,5],
        [6,7,8],
    ];
```

- use `addEventListener` insted of `onclick`

**Comment by Sseryyz** [comment]
> check win conditions over using stored win-lines in arrays, like

Done

**Comment by Sseryyz** [comment]
> use addEventListener insted of onclick
> done

**Comment by Sseryyz** [comment]
> use addEventListener insted of onclick
>Done

**Comment by Sseryyz** [comment]
>use addEventListener insted of onclick
>
Done

**Comment by Sseryyz** [comment]
>replace html from js to template-tags (no ...innerHtml += "<div>...</div>")
>
Done

**Comment by Sseryyz** [comment]
>move all html creation to js
>
Done
